2020-12-09 13:46:47,889     WARNING      server_oop.py        50    server stopped by user
2020-12-09 13:46:48,132     WARNING      server_oop.py        18    server starts with 127.0.0.1:9035
2020-12-09 13:46:48,132     DEBUG        server_oop.py        20    server successfully started socket <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
2020-12-09 13:46:48,133     DEBUG        server_oop.py        22    server successfully got socket
2020-12-09 13:46:48,133     DEBUG        server_oop.py        27    server started to listen socket
2020-12-09 13:46:51,644     DEBUG        server_oop.py        35    server got message from <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9035), raddr=('127.0.0.1', 50189)>
2020-12-09 13:46:51,644     INFO         server_oop.py        38    server got 1 messages since has been started
2020-12-09 13:46:51,645     DEBUG        server_oop.py        56    Checking presence from <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9035), raddr=('127.0.0.1', 50189)>: {'action': 'presence', 'time': 1607510811.625588, 'user': {'account_name': 'Guest'}}
2020-12-09 13:46:51,645     INFO         server_oop.py        59    created answer to client - {'response': 200}
2020-12-09 13:46:51,658     DEBUG        server_oop.py        39    the function "check_presence" with params "({'action': 'presence', 'time': 1607510811.625588, 'user': {'account_name': 'Guest'}},)", "{}" has been ordered from module "__main__", called from "save_to_log"
2020-12-09 13:46:51,659     DEBUG        server_oop.py        39    (from class) the function "self.response=self.check_presence(self.message)" with params (<__main__.Server object at 0x7f807186baf0>, {'action': 'presence', 'time': 1607510811.625588, 'user': {'account_name': 'Guest'}}), {} has been ordered from module <module '__main__' from '/Users/tzverev/PycharmProjects/messenger/lesson_6/server_oop.py'>, called from "start"
2020-12-09 13:46:51,659     DEBUG        server_oop.py        68    message sent to <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9035), raddr=('127.0.0.1', 50189)> with {'response': 200}
2020-12-09 13:46:51,659     DEBUG        server_oop.py        69    connection closed to <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9035), raddr=('127.0.0.1', 50189)>
2020-12-09 13:46:51,660     DEBUG        server_oop.py        40    the function "send" with params "(<socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>, {'response': 200})", "{}" has been ordered from module "__main__", called from "save_to_log"
2020-12-09 13:46:51,661     DEBUG        server_oop.py        40    (from class) the function "self.send(self.client,self.response)" with params (<__main__.Server object at 0x7f807186baf0>, <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>, {'response': 200}), {} has been ordered from module <module '__main__' from '/Users/tzverev/PycharmProjects/messenger/lesson_6/server_oop.py'>, called from "start"
2020-12-09 13:46:51,661     DEBUG        server_oop.py        41    message sent to <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>
2020-12-09 13:46:56,225     WARNING      server_oop.py        50    server stopped by user
